config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  resources :reservations, only: [:new, :create], as: 'reservas'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  get "/eventos/new" => 'events#new', :as => :new_event 
  post "/eventos" => 'events#create', :as => :events 

  scope :admin do
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :rooms do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :reservations, except: [:new, :create] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    
  end


  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'


end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
	layout 'layouts/frontend/application'
	
  def index
  	@rooms = Room.all
  end

end

app/views/frontend/_about.html.haml
%section#about
	.about-container
		.text-about
			.reservation-box
				= form_tag({controller: "reservations", action: "new"}, method: "get") do
					.row
						.col-lg-4.col-md-4.col-sm-4.col-xs-6{style: "margin: 0; padding: 0;"}
							.input-about
								%i.fa.fa-calendar
								= text_field_tag :checkin, nil, :placeholder => "Check-in", class: "datepicker"
						.col-lg-4.col-md-4.col-sm-4.col-xs-6{style: "margin: 0; padding: 0;"}
							.input-about
								%i.fa.fa-calendar
								= text_field_tag :checkout, nil, :placeholder => "Check-out", class: "datepicker"
						.col-lg-4.col-md-4.col-sm-4.col-xs-12
							%button.btn-reservation
								RESERVAR

			#title-about
				¡RESPIRA EL MAR!

			.row#content-about
				.col-lg-6.col-md-6.col-sm-6.col-xs-12
					Nuestra ubicación privilegiada a orillas del mar te ofrecen la oportunidad de desconectar el estrés y vivir de cerca la frescura del mar. Ubicados en Villa Marina, playa por excelencia preferida por los turistas que visitan la Península de Paraguaná.
				.col-lg-6.col-md-6.col-sm-6.col-xs-12
					Ven y vive la experiencia de vivir y respirar el mar de cerca, con la mejor atención, excelentes instalaciones para tus eventos, habitaciones con todas las comodidades, gastronomía en nuestro RESTAURANTE y sobre la mejor atención.

			.info
				.info-hours
					.check-in
						CHECK IN
						%span 01:00 PM
					.check-out
						CHECK OUT
						%span 12:00 PM

#events
	.event-horizontal
		.event-vertical
			.container
				.cont-eventos
					.title-events
						VIVE TUS EVENTOS
						%br
						%span A ORILLAS DEL MAR
					.content-events
						Ofrecemos un salón interno para
						%span 60 personas
						y un área privada a la orilla del mar para
						%span 120 personas,
						adaptada a tus necesidades desde un evento corporativo hasta un evento social.
					.info-event
						= link_to new_event_path do
							PLANIFICA TU EVENTO

app/views/frontend/_contacts.html.haml
%section#contacts
	.separator
		.separator-map
			.title-separator
				¡ENCUENTRANOS!
			.txt-separator
				Calle Monagas, Sector La Puntica, Villa Marina. Estado Falcón.

	#map

	.cont-contacts
		.separator
			.separator-contacts
				.tittle-separator
					¡CONTÁCTANOS!
		.row#contact
			.col-lg-4.col-md-4.hidden-sm.hidden-xs{style: "padding: 0;"}
				= image_tag 'frontend/Logo_VillaMarina.png', id: "logo-footer"
			.col-lg-4.col-md-4.col-sm-6.col-xs-12.icons{style: "padding: 0;"}
				.col-lg-3.col-md-3.col-sm-3.col-xs-3
					= link_to "http://www.instagram.com/posadavillamarina" do
						%i.fa.fa-instagram.socials#instagram
				.col-lg-3.col-md-3.col-sm-3.col-xs-3
					= link_to "http://www.twitter.com/posadavmbr" do
						%i.fa.fa-twitter.socials#twitter
				.col-lg-3.col-md-3.col-sm-3.col-xs-3
					= link_to "http://www.facebook.com/posadavillamarina" do
						%i.fa.fa-facebook.socials#facebook
				.col-lg-3.col-md-3.col-sm-3.col-xs-3
					= link_to "" do
						= image_tag "frontend/Icono_TripAdvisor.png", class: "socials", id: "tripadvisor"

				reservas@posadavillamarina.com
			.col-lg-4.col-md-4.col-sm-6.col-xs-12.numbers
				Números de Contactos
				%br
				0412
				%span 123-77-66
				%br
				0424
				%span 695-55-31
				%br
				0412
				%span 174-84-45

app/views/frontend/_home.html.haml
%section.front#home
	.front-container
		.front-logo-horizontal
			.front-logo-vertical
				
				- if flash[:notice]
					.container
						.alert.alert-success 
							%center{"data-dismiss"=>"alert", "aria-hidden"=>"true"}
								= "<strong>#{flash[:notice]}</strong>".html_safe
								%br Pronto nos estaremos comunicando contigo vía e-mail.

				= image_tag 'frontend/Logo_VillaMarina.png', id: "logo"
				.text-home
					#txt-home
						TU PUNTO VACACIONAL EN 
						%br
						PARAGUANA POR EXCELENCIA

app/views/frontend/_modal.html.haml
#Modal
	%center
	.modal{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1", id: "modal-#{room.id}"}
		.background-modal
			.modal-dialog.modal-lg
				.modal-content
					
					%button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
						%span{"aria-hidden" => "true"} &times;
					.clearfix

					.gallery-modal{id: "gallery-#{room.id}"}
						- room.images.each do |image|
							.img-gallery
								= image_tag image.img 

					.info
						.modal-title
							= room.name.upcase
						.modal-description
							= room.description
						%hr
						%span PRECIO POR NOCHE
						%br/
						Bs
						= room.price
						%br/
						= link_to new_reserva_path do
							RESERVAR	

:javascript
	$("#modal-#{room.id}").on('shown.bs.modal', function (e) {
	  $('#gallery-#{room.id}').slick({
			infinite: true,
			arrows: true,
			autoplay: true,
			autoplaySpeed: 2000,
		});
	})

app/views/frontend/_rooms.html.haml
%section#rooms
	.separator
		.separator-rooms
			CONOCE NUESTRAS CONFORTABLES HABITACIONES
	.gallery
		.container{style: "width: 100%;"}
			.row
				- @rooms.each_with_index do |room, x|
					.col-lg-6.col-md-6.col-sm-6.col-xs-12.col-room{id: "col-room-#{x+1}", style: "background-image: url(#{room.images.first.img});"}
						.mask-rooms{id: "room-#{x+1}"}
							.content-room
								= room.name
								%br
								%li
									= link_to "#modal-#{room.id}" , "data-toggle"=>"modal" do
										VER MÁS

					= render 'modal', room: room

app/views/frontend/_tripAdvisor.html.haml
#tripAdvisor
	.row{ style: " margin: 0; padding: 0; " }
		.col-lg-4.col-md-4.col-sm-4.col-xs-12.txt-tripAdvisor
			¡CUENTANOS TU EXPERIENCIA CON NOSOTROS!
			= link_to "" do
				Déjanos tu historia aquí
		.col-lg-4.col-md-4.col-sm-4.hidden-xs.pareja
			= image_tag 'frontend/Pareja.png', id: "pareja-ta"
		.col-lg-3.col-md-3.col-sm-3.col-xs-12.logo-tripAdvisor
			= image_tag 'frontend/Logo_TripAdvisor.png', id: "logo-ta"

app/views/frontend/_wilmored.html.haml
%section#restaurant
	.wilmored-carousel-big
		.item#item1
		.item#item2

	.wilmored-container
		= image_tag 'frontend/Logo_VillaMarina.png'
		.info-wilmored
			.txt-wilmored
				EXCELENTE COMIDA CON UNA GRAN VISTA

app/views/frontend/index.html.haml
= render "home"
= render 'layouts/frontend/navigation'
= render "about"
= render "rooms"
= render "wilmored"
= render "tripAdvisor"
= render "contacts"