config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  resources :reservations, only: [:new, :create], as: 'reservas'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  get "/eventos/new" => 'events#new', :as => :new_event 
  post "/eventos" => 'events#create', :as => :events 

  scope :admin do
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :rooms do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :reservations, except: [:new, :create] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    
  end


  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'


end

app/models/reservation.rb
#Generado por keppler
require 'elasticsearch/model'
class Reservation < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  has_many :rooms, through: :orders
  has_many :orders
  accepts_nested_attributes_for :orders, :reject_if => :all_blank, :allow_destroy => true
  validates_presence_of :name, :documentation, :email, :telephone, :adults, :checkin, :checkout
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create, :message => "Formato inválido" }
  validates :telephone, :format => { :with => /\d{11}/, :on => :create, :message => "Formato inválido" }
  validate :validates_rooms, :validate_fields, :valid_check_in, :valid_date_range_required, :orders_filter

  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name:  self.name,
      documentation:  self.documentation,
      email:  self.email,
      telephone:  self.telephone,
      adults:  self.adults.to_s,
      kids:  self.kids.to_s,
      babies:  self.babies.to_s,
      origin:  self.origin,
      motive:  self.motive,
      checkin:  self.checkin,
      checkout:  self.checkout,
      payment:  self.payment.to_s,
      observations:  self.observations,
    }.as_json
  end

  def reservation_days
    (self.checkout.to_date - self.checkin.to_date).to_i
  end

  def total_price_for_night
    self.orders.inject(0){ |total, item | total += item.quantity.to_i * item.room.price.to_i }
  end

  def price_total
    self.total_price_for_night*reservation_days
  end

  def orders_filter
    self.orders.each do |order|
      if order.quantity.blank?
        self.orders.delete(order)
      end     
    end
  end

  def valid_date_range_required
    unless self.checkin.blank? or self.checkout.blank?
      errors.add(:checkout, "El check-out no puede ser despues del check-in") if self.checkin > self.checkout
    end
  end

  def valid_check_in
    unless self.checkin.blank? or self.checkout.blank?
      errors.add(:checkin, "El check-in que usted ingresó no es valido") if self.checkin < Date.parse(Time.new.to_s)
      errors.add(:checkout, "El check-in que usted ingresó no es valido") if self.checkout < Date.parse(Time.new.to_s)
    end
  end

  def validates_rooms
    room_hash = []
    self.orders.each do |order|
      unless order.quantity.blank?
        room_hash << order.quantity
      end
    end
    if room_hash.blank?
      errors.add(:orders, "Debe elegir una habitación")
    end
  end

  def validate_fields
    errors.add(:payment, "Debe elegir una forma de pago") if self.payment == 0
    errors.add(:errors, "La cantidad de Niños es inválida") if self.kids.to_i < 0
    errors.add(:errors, "La cantidad de Bebes es inválida") if self.babies.to_i < 0
    errors.add(:errors, "La cantidad de Adultos es inválida") if self.adults.to_i < 1
  end

end
#Reservation.import

app/controllers/reservations_controller.rb
#Generado con Keppler.
class ReservationsController < ApplicationController  
  before_filter :authenticate_user!, except: [:new, :create]
  layout :resolve_layout
  load_and_authorize_resource except: [:new, :create]
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  def index
    reservations = Reservation.searching(@query).all
    @objects, @total = reservations.page(@current_page), reservations.size
    redirect_to reservations_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /reservations/1
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new(checkin: params[:checkin], checkout: params[:checkout])
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  def create
    puts params
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to root_path, notice: reservation_params[:name]+', Su solicitud de reserva debe ser confirmada.'
      ReservationMailer.reservation_email(reservation_params, "http://localhost:3000/admin/reservations/#{Reservation.last.id}").deliver_now
    else
      render :new
    end
  end

  # PATCH/PUT /reservations/1
  def update
    if @reservation.update(reservation_params)
      redirect_to @reservation, notice: 'Reservation was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /reservations/1
  def destroy
    @reservation.destroy
    redirect_to reservations_url, notice: 'Reservation was successfully destroyed.'
  end

  def destroy_multiple
    Reservation.destroy redefine_ids(params[:multiple_ids])
    redirect_to reservations_path(page: @current_page, search: @query), notice: "Reservaciones eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def reservation_params
      params.require(:reservation).permit(:name, :documentation, :email, :telephone, :adults, :kids, :babies, :origin, :motive, :checkin, :checkout, :payment, :observations, orders_attributes: [:id, :room_id, :quantity, :_destroy])
    end

    def resolve_layout
      case action_name
      when "destroy", "update", "edit", "show", "index"
        'admin/application'
      else
        'frontend/application'
      end
    end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Aquí podrá gestionar todos las reservaciones solicitadas mediante la web. Ofrece opciones para editar, eliminar y visualizar las solicitudes.

app/views/reservations/_form.html.haml
#banner-form

#form-reservation
	= simple_form_for @reservation, url: reservas_path  do |f|
		.title-form
			DATOS PERSONALES 

		.row
			.col-lg-6.col-md-6.col-sm-6.col-xs-12
				= f.input :name, label: false, placeholder: "NOMBRE Y APELLIDO"
			.col-lg-6.col-md-6.col-sm-6.col-xs-12
				= f.input :documentation, label: false, placeholder: "CÉDULA DE IDENTIDAD O PASAPORTE"
			.col-lg-6.col-md-6.col-sm-6.col-xs-12
				= f.input :email, label: false, placeholder: "CORREO ELECTRÓNICO"
			.col-lg-6.col-md-6.col-sm-6.col-xs-12
				= f.input :telephone, label: false, placeholder: "NÚMERO DE TELÉFONO"

		.title-form
			DATOS DE RESERVACIÓN

		.row
			.col-lg-4.col-md-4.col-sm-12.col-xs-12
				.col-lg-12.col-md-12.col-sm-4.col-xs-4
					= f.input :adults, label: false, placeholder: "N° ADULTOS", input_html: { min: 0 }
				.col-lg-6.col-md-6.col-sm-4.col-xs-4
					= f.input :kids, label: false, placeholder: "N° NIÑOS", input_html: { min: 0 }
				.col-lg-6.col-md-6.col-sm-4.col-xs-4
					= f.input :babies, label: false, placeholder: "N° BEBES", input_html: { min: 0 }
			.col-lg-4.col-md-4.col-sm-12.col-xs-12
				.col-lg-12.col-md-12.col-sm-6.col-xs-6
					= f.input :checkin, label: false, placeholder: "CHECK-IN", as: :string, input_html: {class: "datepicker", id: "checkin" }
				.col-lg-12.col-md-12.col-sm-6.col-xs-6
					= f.input :checkout, label: false, placeholder: "CHECK-OUT", as: :string, input_html: {class: "datepicker", id: "checkout"}
			.col-lg-4.col-md-4.col-sm-12.col-xs-12
				= f.input :origin, label: false, placeholder: "PROCEDENCIA"
				= f.input :motive, label: false, placeholder: "MOTIVO"
		
		.title-form
			TIPO DE HABITACIÓN 

		.row{style: ""}
			- Room.all.each_with_index do |room, i|
				.room-checks.col-lg-2.col-md-2.col-sm-2.col-xs-2
					= f.simple_fields_for :orders, @reservation.orders.build do |r|
						%a.btn.btn-room{onclick: "quantity(#{room.id})"}
							#image-room{class: "check-#{room.name}", style: "background-image: url(#{room.images.first.img});"}
								= r.input :room_id, label: false, :collection => [[room.name, room.id]], :as => :check_boxes, include_hidden: false, input_html: { name: "reservation[orders_attributes][#{i}][room_id]"}  
							.image-room-mask{id: "mask-#{room.id}"}
								%p
									= room.name.upcase
						.quantity{id: "id-#{room.id}"}
							= r.input :quantity, label:false, placeholder: "Cantidad"
						.room-price{id: "price-#{room.id}"}
							= room.price
							Bs
		.row
			.col-lg-6.col-md-6.col-sm-6.col-xs-12
				.box-form
					.title-box
						METODOS DE PAGO
					.content-box
						= f.input :payment, as: :select, include_blank: false, collection: [["TIPO DE PAGO", "0"], ["TARJETA DE CRÉDITO","1"], ["DEPOSITO Y/O TRANSFERENCIA", "2"], ["EFECTIVO","3"]], label: false
			.col-lg-6.col-md-6.col-sm-6.col-xs-12
				.box-form
					.title-box
						TOTAL DE RESERVA
					.content-box#total
						%table
							%tbody
								%tr
									%td
										Número de habitaciones: 
									%td#num-rooms
										0
								%tr
									%td
										Precio total (Por noche): 
									%td#price-night
										0 Bs
								%tr
									%td
										Total a pagar: 
									%td#price-total
										0 Bs
		.row
			.col-lg-12
				= f.input :observations, label: false, placeholder: "OBSERVACIONES"
		.form-actions
			= f.button :submit, "Guardar", class: "btn btn-save", id: "btn-submit" , style: "width: auto;", controller: "reservation", action: "create"

:javascript
	$('#btn-submit').click(function(){
		setTimeout("$('#btn-submit').prop('disabled', 'disabled')", 10);
	});

app/views/reservations/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Reservation
			= link_to edit_reservation_path(@reservation), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @reservation.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.documentation")
			.display-value= @reservation.documentation
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.email")
			.display-value= @reservation.email
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.telephone")
			.display-value= @reservation.telephone
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.checkin")
			.display-value= @reservation.checkin.strftime("%d-%m-%Y")
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.checkout")
			.display-value= @reservation.checkout.strftime("%d-%m-%Y")
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.adults")
			.display-value= @reservation.adults
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.kids")
			.display-value= (@reservation.kids.blank? or @reservation.kids.zero?) ? "N/A" : @reservation.kids
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.babies")
			.display-value= (@reservation.babies.blank? or @reservation.babies.zero?) ? "N/A" : @reservation.babies
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.origin")
			.display-value= @reservation.origin
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.motive")
			.display-value= @reservation.motive
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.payment")
			- if @reservation.payment == 1
				.display-value Tarjeta de crédito
			- elsif @reservation.payment == 2
				.display-value Depósito o Transferencia
			- else 
				.display-value Efectivo
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.observations")
			.display-value= @reservation.observations.blank? ? "N/A" : @reservation.observations
	
:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/reservations/_listing.html.haml
%tr{ id: "row-#{reservation.id}" }
	- if can? :destroy_multiple, Reservation
		%td.item-check{style:"width: 10%"}
			= link_to "", reservation_path(reservation), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{reservation.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{reservation.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{reservation.id}" }
		%td
			= link_to "", reservation_path(reservation, search: @query), remote: true, class: "show-row"
			%span
				= reservation.name
		%td.hide-on-small-and-down
			= link_to "", reservation_path(reservation, search: @query), remote: true, class: "show-row"
			%span
				= reservation.documentation
		%td.hide-on-small-and-down
			= link_to "", reservation_path(reservation, search: @query), remote: true, class: "show-row"
			%span
				= reservation.telephone
		%td
			= link_to "", reservation_path(reservation, search: @query), remote: true, class: "show-row"
			%span
				= reservation.created_at.strftime("%d-%m-%Y %H:%M ")
								
	%td{style:"width: 5%"}		
		= link_to reservation_path(reservation), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/reservations/edit.html.haml
= title "Reservaciones - Editar | #{@reservation.id}"
= render 'form'

app/views/reservations/index.html.haml
= title("Reservaciones - Listado")
.listing.col.l9.m12.s12
	
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |reservation|
				= render 'listing', reservation: reservation
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado reservaciones.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

app/views/reservations/new.html.haml
= title "Reservaciones - Nueva Reservacion"

= render 'layouts/frontend/navigation'
= render 'form'

app/views/reservations/show.html.haml
= title "Reservaciones | #{@reservation.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Reservation
				= link_to reservation_path(@reservation), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: '¿Está seguro de querer eliminar?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			= link_to reservations_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		
		.panel-body#body-show.order-reservation-show
			.container
				%table.table.table-bordered
					%tr
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.name")
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.email")
					%tr
						%td{ colspan: '2' }
							= @reservation.name
						%td{ colspan: '2' }
							= @reservation.email
					%tr
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.documentation")
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.telephone")
					%tr
						%td{ colspan: '2' }
							= @reservation.documentation
						%td{ colspan: '2' }
							= @reservation.telephone
					%tr
						%th{ colspan: '1' }
							= t("model.#{controller_name.singularize}.attributes.adults")
						%th{ colspan: '1' }
							= t("model.#{controller_name.singularize}.attributes.kids")
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.babies")
					%tr
						%td{ colspan: '1' }
							= @reservation.adults
						%td{ colspan: '1' }
							= (@reservation.kids.blank? or @reservation.kids.zero?) ? "N/A" : @reservation.kids
						%td{ colspan: '2' }
							= (@reservation.babies.blank? or @reservation.babies.zero?) ? "N/A" : @reservation.babies
					%tr
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.origin")
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.motive")
					%tr
						%td{ colspan: '2' }
							= @reservation.origin
						%td{ colspan: '2' }
							= @reservation.motive
					%tr
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.checkin")
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.checkout")
					%tr
						%td{ colspan: '2' }
							= @reservation.checkin.strftime("%d-%m-%Y")
						%td{ colspan: '2' }
							= @reservation.checkout.strftime("%d-%m-%Y")
					%tr
						%th{ colspan: '4' }
							= t("model.#{controller_name.singularize}.attributes.payment")
					%tr
						%td{ colspan: '4' }
							- if @reservation.payment == 1
								Tarjeta de crédito
							- elsif @reservation.payment == 2
								Depósito o Transferencia
							- else 
								Efectivo
					%tr
						%th{ colspan: '4' }
							= t("model.#{controller_name.singularize}.attributes.observations")
					%tr
						%td{ colspan: '4' }
							= @reservation.observations.blank? ? "N/A" : @reservation.observations
					%tr
						%th{ colspan: '1' } 
							Habitación
						%th{ colspan: '1' } 
							Cantidad
						%th{ colspan: '2' } 
							Precio
					%tr
						- @reservation.orders.each do |item|
							%tr
								%td{ colspan: '1'}
									= item.room.name
								%td{ colspan: '1'}
									= item.quantity
								%td{ colspan: '2'}
									= number_to_currency(item.room.price, precision: 2, format: "%u %n", unit: "Bs.")
					%tr
						%th{ colspan: '3' } 
							Total por noche
						%th.red.lighten-5{ colspan: '1' }
							= number_to_currency(@reservation.total_price_for_night, precision: 2, format: "%u %n", unit: "Bs.")
							
					%tr
						%th{ colspan: '3' } 
							Total por estadía
						%th.blue.lighten-5{ colspan: '1' }
							= number_to_currency(@reservation.price_total, precision: 2, format: "%u %n", unit: "Bs.")

app/views/reservations/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@reservation.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");