config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  resources :reservations, only: [:new, :create], as: 'reservas'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  get "/eventos/new" => 'events#new', :as => :new_event 
  post "/eventos" => 'events#create', :as => :events 

  scope :admin do
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :rooms do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :reservations, except: [:new, :create] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    
  end


  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'


end

app/models/room.rb
#Generado por keppler
require 'elasticsearch/model'
class Room < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  before_save :create_permalink
  has_many :images, :dependent => :destroy
  has_many :reservations, through: :orders
  has_many :orders
  accepts_nested_attributes_for :images, :reject_if => :all_blank, :allow_destroy => true
  validates_presence_of :name, :price, :description


  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:id, :name, :price, :desription] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name:  self.name,
      price:  self.price.to_s,
      description:  self.description,
    }.as_json
  end

  def create_permalink
    self.permalink=self.name.downcase.parameterize
  end

end

#Room.import

app/controllers/rooms_controller.rb
#Generado con Keppler.
class RoomsController < ApplicationController  
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  def index
    rooms = Room.searching(@query).all
    @objects, @total = rooms.page(@current_page), rooms.size
    redirect_to rooms_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /rooms/1
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to @room, notice: 'Habitación creada satisfactoriamente.'
    else
      render :new
    end
  end

  # PATCH/PUT /rooms/1
  def update
    if @room.update(room_params)
      redirect_to @room, notice: 'Habitación editada satisfactoriamente.'
    else
      render :edit
    end
  end

  # DELETE /rooms/1
  def destroy
    @room.destroy
    redirect_to rooms_url, notice: 'Habitación eliminada satisfactoriamente.'
  end

  def destroy_multiple
    Room.destroy redefine_ids(params[:multiple_ids])
    redirect_to rooms_path(page: @current_page, search: @query), notice: "Habitaciones eliminadas satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def room_params
      params.require(:room).permit(:name, :price, :description, images_attributes: [:id, :img, :_destroy])
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} En esta sección se pueden ver las habitaciones de las cuales dispone la posada.

app/views/rooms/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to rooms_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")

		.wrapper-inputs
			.card
				= simple_form_for @room do |f|
					.row
						= f.input :name
						= f.input :price
						= f.input :description, input_html: {class: "materialize-textarea"}
					.row
						= f.simple_fields_for :images do |c|
							= render 'image_fields', :f => c
							
						.form-actions.right
							= link_to_add_association 'Añadir imagen', f, :images, class: "waves-effect waves-dark btn-flat", style: "margin-bottom:10px;"
							= f.button :submit, "Guardar", class: "btn"

app/views/rooms/_image_fields.html.haml
.nested-fields.col.s4
	- unless f.object.img.to_s == ""
		= image_tag f.object.img, style: "width: 100%"
	
	= link_to_remove_association f do
		= material_icon.md_24.close.css_class('md-dark')

	= f.input :img, :as => :file, label: false, wrapper: :mf_11, class: "upload_file"

app/views/rooms/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Room
			= link_to edit_room_path(@room), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.card-image
		- if @room.images.any?
			= image_tag @room.images.first.img
			
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @room.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @room.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.price")
			.display-value= @room.price
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.description")
			.display-value= @room.description
	

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/rooms/_listing.html.haml
%tr{ id: "row-#{room.id}" }
	- if can? :destroy_multiple, Room
		%td.item-check{style:"width: 10%"}
			= link_to "", room_path(room), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{room.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{room.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{room.id}" }

		%td{style:"width: 30%"}
			= link_to "", room_path(room, search: @query), remote: true, class: "show-row"
			%span
				= room.name
		%td{style:"width: 30%"}
			= link_to "", room_path(room, search: @query), remote: true, class: "show-row"
			%span
				= room.price
								
	%td{style:"width: 5%"}		
		= link_to room_path(room), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/rooms/edit.html.haml
= title "Rooms - editar | #{@room.id}"
= render 'form'

app/views/rooms/index.html.haml
= title("Rooms - Listado")
.listing.col.l9.m12.s12
	= link_to new_room_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
		= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |room|
				= render 'listing', room: room
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado rooms.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"


= link_to new_room_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
	= material_icon.md_24.add.css_class("md-light")

app/views/rooms/new.html.haml
= title "Rooms - Nuevo"
= render 'form'

app/views/rooms/show.html.haml
= title "Rooms | #{@room.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Room
				= link_to room_path(@room), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Room
				= link_to edit_room_path(@room), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to rooms_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card#show-room	
			- if @room.images.any?
				.card-image
					.slider
						%ul.slides
							- @room.images.each do |item|
								%li
									= image_tag item.img
			
			.card-content		
				%ul.list
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.id")
						.display-value.fs-body-1.tc-black-2= @room.id.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.name")
						.display-value.fs-body-1.tc-black-2= @room.name.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.price")
						.display-value.fs-body-1.tc-black-2= @room.price.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.description")
						.display-value.fs-body-1.tc-black-2= @room.description.to_s.humanize


:javascript	
	$(document).ready(function(){
		$('.slider').slider();
	});

app/views/rooms/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@room.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");